### ISSUE TITLE
compiling Quickcollider with SuperCollider 3.7alpha1

### ISSUE THREAD

**Issue by nuss** [jleben/quickcollider#2]
Hi Jakob,

I've just tried to compile Quickcollider under Ubuntustudio 14.04 and failed with the following error (following a long list of more errors which I believe are the consequence of this first one):
```
[  2%] Building CXX object CMakeFiles/quickcollider.dir/gui/widgets/oscilloscope.cpp.o
In file included from /usr/include/c++/4.8/atomic:38:0,
                 from /home/stefan/sources/supercollider/common/scope_buffer.hpp:24,
                 from /home/stefan/sources/supercollider/common/server_shm.hpp:23,
                 from /home/stefan/sources/quickcollider/gui/widgets/oscilloscope_shm.hpp:26,
                 from /home/stefan/sources/quickcollider/gui/widgets/oscilloscope.cpp:23:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```
Do you know if it's still possible to compile Quickcollider with the current development-version of SuperCollider (3.7alpha1)?

Thanks, Stefan

**Comment by jleben** [comment]
Yes - the SuperCollider header file requires C++11 support, which should be enabled in the CMake build system of QuickCollider.

Can you please tell me more about your system:
- operating system version?
- compiler version?
- CMake version?

Also, in future, questions like this should be sent in an email to me, rather than opening a GitHub issue. It is best practice for any software project to first confirm whether something is an issue of the project before entering it into the issue tracker.

**Comment by nuss** [comment]
ok

- operating system: Ubuntustudio 14.04 (x86_64 GNU/LINUX)
- compiler:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
- CMake version: cmake version 2.8.12.2

I've used this configuration to compile SuperCollider up to the current day without a problem. I thought it should handle c++11. What else could be the problem?

**Comment by jleben** [comment]
Yes, it will handle C++11, but this has to be explicitly enabled in the CMake build system. (In the CMakeLists.txt file). I will send you some code to try soon...

**Comment by jleben** [comment]
I created another branch named "enable-cpp11". Can you please try it?

**Comment by nuss** [comment]
I tried that branch and I made some advance - compilation went up to 100% but then I get some linking-error. However, I'm going close this issue now (the recent linking-error doesn't seem to be related to my problem in the first place) and send you an email. Thanks!
